In [1]:
import torch
import numpy as np

OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。 Error loading "C:\Users\RockyChen\AppData\Roaming\Python\Python312\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [2]:
# 1------ 创建张量 --------
# torch.tensor【掌握】
# 1.1- 标量张量
t1 = torch.tensor(999)
print(type(t1))
print(t1)

<class 'torch.Tensor'>
tensor(999)


In [4]:
# 1.2- 基于numpy创建张量
# 张量的整数默认类型是int32
arr1 = np.random.randint(low=1,high=10,size=(2,3))
t2 = torch.tensor(arr1)
t2

tensor([[5, 8, 3],
        [4, 9, 8]], dtype=torch.int32)

In [5]:
# 1.3- 通过容器创建张量
t3 = torch.tensor([11,22,33])
t3

tensor([11, 22, 33])

In [7]:
# 注意：张量只能处理数值，不能处理非数字
# t4 = torch.tensor("hello")
t4 = torch.tensor("999")
t4

TypeError: new(): invalid data type 'str'

In [9]:
# 注意：小写的tensor中如下的形式2、3是当成元素值使用，而不是形状
t5 = torch.tensor([2,3])
t5

tensor([2, 3])

In [31]:
# torch.Tensor创建张量
# 如果值的外面不加中括号，那么当成size形状使用，而不是当成元素值使用
t6 = torch.Tensor(9)
t6

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
t6 = torch.Tensor([9])
t6

tensor([9.])

In [12]:
t7 = torch.Tensor([2,3])
t7

tensor([2., 3.])

In [14]:
# 创建指定类型的张量
# t8 = torch.IntTensor(2,3)
t8 = torch.IntTensor([2,3])
t8

tensor([2, 3], dtype=torch.int32)

In [15]:
# 如果传递的元素类型与要求的类型不匹配，那么会自动的进行类型转换。float->int的时候，只保留整数部分
t9 = torch.IntTensor([1.99,2.88,3.66,4.44])
t9

tensor([1, 2, 3, 4], dtype=torch.int32)

In [17]:
# t10 = torch.FloatTensor([1.99,2.88,3.66,4.44])
t10 = torch.FloatTensor([1,2,3,4])
t10

tensor([1., 2., 3., 4.])

In [18]:
t11 = torch.ShortTensor([1.99,2.88,3.66,4.44])
t11

tensor([1, 2, 3, 4], dtype=torch.int16)

In [19]:
t11 = torch.LongTensor([1.99,2.88,3.66,4.44])
t11

tensor([1, 2, 3, 4])

In [2]:
# 2------ 创建线性张量 -------
# arange(start,end,step)：区间是[start,end)
t12 = torch.arange(1,10)
t12

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# torch.linspace(start,end,steps)：区间[start,end]，注意steps表示的是元素个数
t13 = torch.linspace(start=1,end=10,steps=5)
t13

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [12]:
# 3------- 随机张量 --------
# print("初始化随机数种子",torch.random.initial_seed())

# 手动设置随机数种子。作用：是让生成的随机数固定
torch.random.manual_seed(1013)

t14 = torch.rand(size=[2,3])
print(t14)
print(t14.dtype)

tensor([[0.6019, 0.8239, 0.1237],
        [0.9589, 0.5808, 0.2052]])
torch.float32


In [17]:
torch.random.manual_seed(1013)
t15 = torch.randn(size=[2,3])
t15

tensor([[ 1.2050, -2.7827, -0.2133],
        [-0.2788, -1.5143, -0.4005]])

In [18]:
# randint(low,high,size)：区间是[low,high)
t16 = torch.randint(low=1,high=5,size=[2,3,4])
t16

tensor([[[4, 2, 4, 2],
         [4, 1, 2, 1],
         [1, 4, 2, 4]],

        [[4, 4, 3, 1],
         [4, 2, 3, 1],
         [1, 2, 2, 3]]])

In [20]:
# 4-------- 创建指定值张量 -------
# t1 = torch.ones(size=(2,3))
t1 = torch.ones(size=[2,3])
t1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
t2 = torch.zeros(size=(2,3))
t2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
t3 = torch.full(size=(2,3),fill_value=999)
t3

tensor([[999, 999, 999],
        [999, 999, 999]])

In [23]:
t0 = torch.randint(low=1,high=10,size=(4,5))
t0

tensor([[7, 2, 5, 6, 9],
        [8, 2, 6, 7, 9],
        [2, 6, 2, 9, 5],
        [6, 3, 1, 1, 7]])

In [24]:
t4 = torch.ones_like(t0)
t4

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [25]:
t5 = torch.zeros_like(t0)
t5

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [26]:
t6 = torch.full_like(t0,fill_value=666)
t6

tensor([[666, 666, 666, 666, 666],
        [666, 666, 666, 666, 666],
        [666, 666, 666, 666, 666],
        [666, 666, 666, 666, 666]])

In [27]:
# 6------ 张量的元素类型转换 -----
t0 = torch.randint(low=1,high=10,size=(4,5))
t0

tensor([[6, 6, 7, 1, 5],
        [3, 2, 3, 4, 6],
        [6, 1, 2, 2, 5],
        [4, 1, 3, 8, 6]])

In [30]:
# 掌握：张量对象.type(dtype=目标类型)
# t1 = t0.type(dtype=torch.FloatTensor)
# t1 = t0.type(dtype=torch.float16)
t1 = t0.type(dtype=torch.int16)
print(t1)
print(t1.dtype)

tensor([[6, 6, 7, 1, 5],
        [3, 2, 3, 4, 6],
        [6, 1, 2, 2, 5],
        [4, 1, 3, 8, 6]], dtype=torch.int16)
torch.int16


In [34]:
# t2 = t0.half() # float16
# t2 = t0.double() # float64。双精度浮点类型
t2 = t0.long() # int64
print(t2)
print(t2.dtype)

tensor([[6, 6, 7, 1, 5],
        [3, 2, 3, 4, 6],
        [6, 1, 2, 2, 5],
        [4, 1, 3, 8, 6]])
torch.int64
