In [1]:
import torch
import numpy as np

In [7]:
# 1------ 张量 转成 numpy的ndarray数组
t0 = torch.randint(low=0,high=10,size=(2,3))
t0

tensor([[3, 7, 7],
        [6, 3, 5]])

In [8]:
# 张量.numpy()转成ndarry数据，会共享内容
# 共享内容
# arr1 = t0.numpy()

# 不共享内容。就是深拷贝
arr1 = t0.numpy().copy()
arr1

array([[3, 7, 7],
       [6, 3, 5]], dtype=int64)

In [9]:
arr1[1][1]=100
arr1

array([[  3,   7,   7],
       [  6, 100,   5]], dtype=int64)

In [10]:
t0

tensor([[3, 7, 7],
        [6, 3, 5]])

In [11]:
# 2------ numpy的ndarray 转成 张量
arr2 = np.array([11,22,33])
arr2

array([11, 22, 33])

In [12]:
# torch.tensor不共享内存
t2 = torch.tensor(arr2)
t2

tensor([11, 22, 33], dtype=torch.int32)

In [13]:
t2[1]=999
t2

tensor([ 11, 999,  33], dtype=torch.int32)

In [14]:
arr2

array([11, 22, 33])

In [15]:
# 共享内存
t3 = torch.from_numpy(arr2)
t3

tensor([11, 22, 33], dtype=torch.int32)

In [16]:
t3[1]=999
t3

tensor([ 11, 999,  33], dtype=torch.int32)

In [17]:
arr2

array([ 11, 999,  33])

In [18]:
# 3------ 张量 转成 标量
t4 = torch.tensor(999)
t4

tensor(999)

In [19]:
result = t4.item()
print(result,type(result))

999 <class 'int'>


In [20]:
# 注意：item()只支持张量中只有一个元素的情况。否则会报错a Tensor with 2 elements cannot be converted to Scalar
# 因此下面的代码会报错
t5 = torch.tensor([11,22])
print(t5.item())

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar