In [1]:
import torch

In [2]:
# 1------ 基础运算 ------
t0 = torch.randint(low=-5,high=5,size=(2,3))
t0

tensor([[ 0,  1,  2],
        [-2,  4, -2]])

In [3]:
# 不带下划线，那么不会对原始张量修改
t1 = t0.add(10)
print(t0)
print(t1)

tensor([[ 0,  1,  2],
        [-2,  4, -2]])
tensor([[10, 11, 12],
        [ 8, 14,  8]])


In [4]:
t2 = t0.sub(10)
t2

tensor([[-10,  -9,  -8],
        [-12,  -6, -12]])

In [5]:
t3 = t0.mul(10)
t3

tensor([[  0,  10,  20],
        [-20,  40, -20]])

In [6]:
t4 = t0.neg()
t4

tensor([[ 0, -1, -2],
        [ 2, -4,  2]])

In [8]:
# 带下划线，那么会对原始张量直接修改
t5 = t0.add_(10)
print(t5)
print(t0)

tensor([[10, 11, 12],
        [ 8, 14,  8]])
tensor([[10, 11, 12],
        [ 8, 14,  8]])


In [12]:
# 推荐掌握直接用符号的形式
t0 = torch.randint(low=-5,high=5,size=(2,3))
# t6 = t0 + 100
# t6 = t0 * 100
t6 = t0 * -1
print(t0)
print(t6)

tensor([[ 0,  3, -3],
        [-5,  0,  1]])
tensor([[ 0, -3,  3],
        [ 5,  0, -1]])


In [13]:
t0+=10 # 等价于t0.add_(10)
t0

tensor([[10, 13,  7],
        [ 5, 10, 11]])

In [15]:
# 2------ 张量点乘运算 -------
# 正确的演示：注意点乘的两个张量的形状必须完全相同
t1 = torch.tensor([[11,22,33],[44,55,66]])
t2 = torch.tensor([[1,2,3],[4,5,6]])
# t3 = t1.mul(t2)
t3 = t1*t2 # 推荐掌握
t3

tensor([[ 11,  44,  99],
        [176, 275, 396]])

In [16]:
# 错误的演示：两个张量形状不同
t1 = torch.tensor([[11,22,33],[44,55,66]])
t2 = torch.tensor([[1,2],[4,5],[7,8]])
t3 = t1*t2
t3

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [19]:
# 3----- 矩阵乘法运算 ------
# 矩阵乘法的前提：是前一个矩阵的列数与后一个矩阵的行数要相同
t1 = torch.tensor([[11,22,33],[44,55,66]]) # 2行3列
t2 = torch.tensor([[1],[4],[7]]) # 3行1列
t4 = t1@t2 # 推荐掌握
# t4 = t1.matmul(t2)
t4

tensor([[330],
        [726]])

In [18]:
t1 = torch.tensor([[11,22,33],[44,55,66]])
t2 = torch.tensor([[1,2,3],[4,5,6]])
t5 = t1@t2
t5

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)