In [1]:
import torch

In [4]:
t0 = torch.randint(low=0,high=10,size=(2,3),dtype=torch.float32)
t0

tensor([[6., 8., 1.],
        [1., 9., 6.]])

In [7]:
"""
    mean(dim)：用来计算元素均值
        dim参数如果不指定，那么是对所有元素计算均值
        
        注意：用来计算均值的张量中，元素的类型必须是小数
"""
# r1 = t0.mean() # 所有元素进行计算
# r1 = t0.mean(dim=0) # 行和行之间计算均值
r1 = t0.mean(dim=1) # 列和列之间计算均值
r1

tensor([5.0000, 5.3333])

In [12]:
r2 = t0.sum() # 所有元素进行计算，得到的值只有一个 # 重点掌握
# r2 = t0.sum(dim=0) # 行和行之间计算求和
# r2 = t0.sum(dim=1) # 列和列之间计算求和
r2

tensor(31.)

In [13]:
t0 = torch.randint(low=0,high=10,size=(2,3),dtype=torch.float32)
t0

tensor([[1., 5., 2.],
        [9., 7., 1.]])

In [19]:
# 了解
# r3 = t0.min()
# r3 = t0.pow(2) # pow中的参数作为幂使用
# r3 = t0.sqrt() # 开根号
# r3 = t0.exp()
r3 = t0.log()

r3

tensor([[0.0000, 2.3219, 1.0000],
        [3.1699, 2.8074, 0.0000]])