In [1]:
import torch

In [2]:
t0 = torch.randint(0,10,(4,5))
t0

tensor([[3, 2, 2, 8, 4],
        [4, 5, 1, 7, 8],
        [0, 5, 5, 4, 1],
        [5, 9, 6, 4, 7]])

In [6]:
# 【掌握】1----- 简单的行、列索引 --------
# r1 = t0[0] # 获取第一行数据
# r1 = t0[:,0] # 获取第一列数据
r1 = t0[:,-1] # 获取最后一列数据
r1

tensor([4, 8, 1, 7])

In [7]:
# 【掌握】2------ 范围索引：与容器中的切片操作完全一样 -------
# 需求1：前3行的前2列数据
r2 = t0[:3,:2]
r2

tensor([[3, 2],
        [4, 5],
        [0, 5]])

In [8]:
# 需求2：第2行到最后的行，并且前2列的数据
r3 = t0[1:,:2]
r3

tensor([[4, 5],
        [0, 5],
        [5, 9]])

In [9]:
r3 = t0[::2,:2] # 同时还支持设置步长
r3

tensor([[3, 2],
        [0, 5]])

In [10]:
# 【了解】3------- 列表索引 -----
# 需求1：返回(0,1)、(1,2)两个位置的元素
#      [[行索引], [列索引]]
r4 = t0[[0,1], [1,2]]
r4

tensor([2, 1])

In [11]:
# 需求2：获取两个元素的坐标是(2,4)、(3,3)
r5 = t0[[2,3], [4,3]]
r5

tensor([1, 4])

In [12]:
# 获取4个元素，坐标分别是(2,4)、(2,3)、(3,4)、(3,3)
r6 = t0[[[2],[3]], [4,3]]
r6

tensor([[1, 4],
        [7, 4]])

In [13]:
t0 = torch.randint(0,10,(4,5))
t0

tensor([[0, 4, 4, 9, 3],
        [4, 0, 7, 5, 9],
        [9, 0, 6, 8, 0],
        [0, 4, 2, 0, 2]])

In [17]:
# 【了解】4------- 布尔索引 -------
# 需求1：第3列大于5的，对应的行数据
"""
    需求拆解：
        1- 取第3列
        2- 对取出的第3列中每个元素判断是否是大于5
        3- 取出对应的行数据
"""
# 1- 取第3列
r6 = t0[:,2]

# 2- 对取出的第3列中每个元素判断是否是大于5
r6 = t0[:,2]>5

# 3- 取出对应的行数据
r6 = t0[t0[:,2]>5]

r6

IndexError: The shape of the mask [4] at index 0 does not match the shape of the indexed tensor [4, 5] at index 1

In [18]:
# 需求2：第二行大于5的，对应的列数据
r7 = t0[:,t0[1]>5]
r7

tensor([[4, 3],
        [7, 9],
        [6, 0],
        [2, 2]])

In [19]:
# 【了解】5------ 多维索引 --------
t1 = torch.randint(0,10,size=(3,4,5))
t1

tensor([[[3, 8, 6, 9, 7],
         [1, 4, 3, 8, 5],
         [8, 7, 0, 4, 2],
         [7, 7, 4, 8, 0]],

        [[0, 5, 1, 2, 2],
         [0, 9, 8, 4, 7],
         [2, 6, 5, 3, 6],
         [6, 6, 8, 6, 2]],

        [[9, 1, 3, 4, 7],
         [9, 1, 1, 5, 9],
         [8, 8, 2, 3, 9],
         [2, 4, 9, 0, 6]]])

In [20]:
# 获取0轴上的数据
r1 = t1[0,:,:]
r1

tensor([[3, 8, 6, 9, 7],
        [1, 4, 3, 8, 5],
        [8, 7, 0, 4, 2],
        [7, 7, 4, 8, 0]])

In [22]:
# 获取1轴上的数据
r2 = t1[:,0,:]
r2

tensor([[3, 8, 6, 9, 7],
        [0, 5, 1, 2, 2],
        [9, 1, 3, 4, 7]])

In [23]:
# 获取2轴上的数据
r3 = t1[:,:,0]
r3

tensor([[3, 1, 8, 7],
        [0, 0, 2, 6],
        [9, 9, 8, 2]])