In [1]:
import torch

In [3]:
# 1------- reshape ------
# 前提：修改前后元素总个数要一致
t0 = torch.tensor([[10,20,30], [40,50,60]])
t0

tensor([[10, 20, 30],
        [40, 50, 60]])

In [5]:
# 获取形状
print(t0.shape,t0.shape[0],t0.shape[1])
print(t0.size(),t0.size(0),t0.size(1))

torch.Size([2, 3]) 2 3
torch.Size([2, 3]) 2 3


In [6]:
# 修改形状
t1 = t0.reshape(6,1)
t1

tensor([[10],
        [20],
        [30],
        [40],
        [50],
        [60]])

In [7]:
t2 = t0.reshape(-1,1)
t2

tensor([[10],
        [20],
        [30],
        [40],
        [50],
        [60]])

In [9]:
# 错误用法。元素个数不一致
# t3 = t0.reshape(6,2)
t3 = t0.reshape(2,2)
t3

RuntimeError: shape '[2, 2]' is invalid for input of size 6

In [17]:
# 2------- squeeze降维和unsqueeze升维 ------
t0 = torch.tensor([[10,20,30], [40,50,60]])
t0

tensor([[10, 20, 30],
        [40, 50, 60]])

In [11]:
# 2.1 unsqueeze升维
t1 = t0.unsqueeze(dim=0)
print(t1.shape) # (2,3) -> (1,2,3)
print(t1)

torch.Size([1, 2, 3])
tensor([[[10, 20, 30],
         [40, 50, 60]]])


In [12]:
t1 = t0.unsqueeze(dim=1)
print(t1.shape) # (2,3) -> (2,1,3)
print(t1)

torch.Size([2, 1, 3])
tensor([[[10, 20, 30]],

        [[40, 50, 60]]])


In [13]:
t1 = t0.unsqueeze(dim=2)
print(t1.shape) # (2,3) -> (2,3,1)
print(t1)

torch.Size([2, 3, 1])
tensor([[[10],
         [20],
         [30]],

        [[40],
         [50],
         [60]]])


In [14]:
# dim参数的值不允许>张量的元素维度个数
t1 = t0.unsqueeze(dim=3)
print(t1.shape) # (2,3) -> (2,3,,1)
print(t1)

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [18]:
t0.unsqueeze_(dim=2) # (2,3,1)
t0.shape

torch.Size([2, 3, 1])

In [19]:
# squeeze降维
t1 = t0.squeeze()
t1.shape # (2,3,1) -> (2,3)

torch.Size([2, 3])

In [26]:
# t1 = t0.squeeze(dim=1) # 将轴索引为1对应的维度，如果形状是1，那么会进行降维；如果形状不是1，那么不会进行降维
t1 = t0.squeeze(dim=2)
t1.shape

torch.Size([2, 3])

In [28]:
t0 = torch.randint(0,10,size=(2,1,3,1,4,1))
t0.shape

torch.Size([2, 1, 3, 1, 4, 1])

In [30]:
# t1 = t0.squeeze() # 如果不传递dim参数，那么将形状为1的全部进行降维
t1 = t0.squeeze(dim=-1) # dim=-1表示将最里层的维度进行降维，当然前提是对应的形状要是1
t1.shape

torch.Size([2, 1, 3, 1, 4])

In [31]:
# transpose和permute：交换形状的位置，维度个数不变
# transpose：同一时刻只能交换两个位置的形状
# permute：同一时刻可以交换任意个位置的形状
# 总结：如果在多个维度的情况下，只需要交换两个位置推荐使用transpose；否则推荐使用permute
t0 = torch.randint(0,10,size=(3,4,5))
t0.shape

torch.Size([3, 4, 5])

In [33]:
# transpose(dim0,dim1)：同一时刻只能交换两个位置的形状
# 参数解释：dim0、dim1表示是对哪两个位置的形状进行交换，不要求参数顺序
# 需求1：(3,4,5) -> (3,5,4)
# t1 = t0.transpose(dim0=1,dim1=2)
t1 = t0.transpose(dim0=2,dim1=1)
t1.shape

torch.Size([3, 5, 4])

In [36]:
# 需求2：(3,4,5) -> (4,5,3)
# 步骤：(3,4,5) -> (4,3,5) -> (4,5,3)
# transpose每调用一次，轴的索引会重置
t2 = t0.transpose(dim0=0,dim1=1).transpose(dim0=1,dim1=2)
t2.shape

torch.Size([4, 5, 3])

In [38]:
# permute：同一时刻可以交换任意个位置的形状
# 需求：(3,4,5) -> (4,5,3)
# 索引：(0,1,2) -> (1,2,0)
t1 = t0.permute(dims=(1,2,0))
t1.shape

torch.Size([4, 5, 3])