In [1]:
import torch

In [3]:
# 1----- cat/concat ------
t0 = torch.randint(low=0,high=10,size=(2,3))
t1 = torch.randint(low=0,high=10,size=(2,3))
t1.backward()
print(t0)
print(t1)

tensor([[6, 9, 6],
        [9, 6, 6]])
tensor([[8, 5, 3],
        [0, 7, 9]])


In [4]:
cat_t1 = torch.cat([t0,t1],dim=0) # 二维张量的情况下，dim=0按行进行拼接
print(cat_t1)
print(cat_t1.shape)

tensor([[6, 9, 6],
        [9, 6, 6],
        [8, 5, 3],
        [0, 7, 9]])
torch.Size([4, 3])


In [5]:
cat_t1 = torch.cat([t0,t1],dim=1) # 二维张量的情况下，dim=1按行进列拼接
print(cat_t1)
print(cat_t1.shape)

tensor([[6, 9, 6, 8, 5, 3],
        [9, 6, 6, 0, 7, 9]])
torch.Size([2, 6])


In [6]:
t0 = torch.randint(low=0,high=10,size=(2,3))
t1 = torch.randint(low=0,high=10,size=(4,3))

print(t0)
print(t1)

tensor([[5, 4, 8],
        [5, 3, 4]])
tensor([[1, 2, 6],
        [5, 4, 2],
        [8, 4, 8],
        [3, 8, 4]])


In [7]:
cat_t1 = torch.cat([t0,t1],dim=0) # 二维张量的情况下，dim=0按行进行拼接
print(cat_t1)
print(cat_t1.shape)

tensor([[5, 4, 8],
        [5, 3, 4],
        [1, 2, 6],
        [5, 4, 2],
        [8, 4, 8],
        [3, 8, 4]])
torch.Size([6, 3])


In [8]:
# 注意：cat/concat拼接的时候，拼接的指定维度/形状不用相同，其他不参与拼接的维度/形状必须相同
t0 = torch.randint(low=0,high=10,size=(2,3))
t1 = torch.randint(low=0,high=10,size=(2,4))

print(t0)
print(t1)

tensor([[8, 4, 9],
        [8, 1, 0]])
tensor([[1, 2, 2, 6],
        [6, 8, 0, 7]])


In [9]:
cat_t1 = torch.cat([t0,t1],dim=0) # 二维张量的情况下，dim=0按行进行拼接
print(cat_t1)
print(cat_t1.shape)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 4 for tensor number 1 in the list.

In [14]:
# 2----- stack --------
# 注意：两个张量的形状必须完全相同。同时拼接后的结果会进行升维
t0 = torch.randint(low=0,high=10,size=(3,4))
t1 = torch.randint(low=0,high=10,size=(3,4))

print(t0)
print(t1)

tensor([[9, 4, 0, 3],
        [7, 2, 8, 1],
        [4, 1, 5, 1]])
tensor([[8, 6, 5, 7],
        [4, 3, 3, 4],
        [8, 4, 9, 4]])


In [18]:
# stack_t1 = torch.stack([t0,t1],dim=0) # 2,3,4
# stack_t1 = torch.stack([t0,t1],dim=1) # 3,2,4
stack_t1 = torch.stack([t0,t1],dim=2) # 3,4,2
print(stack_t1)
print(stack_t1.shape) 

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [19]:
# 注意：两个张量的形状必须完全相同。同时拼接后的结果会进行升维
t0 = torch.randint(low=0,high=10,size=(3,5))
t1 = torch.randint(low=0,high=10,size=(3,4))
stack_t1 = torch.stack([t0,t1],dim=0)
print(stack_t1)
print(stack_t1.shape) 

RuntimeError: stack expects each tensor to be equal size, but got [3, 5] at entry 0 and [3, 4] at entry 1